Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting conda
  Downloading conda-4.3.16.tar.gz (299 kB)
Collecting env
  Downloading env-0.1.0.tar.gz (1.8 kB)
Collecting export
  Downloading export-0.2.0-py3-none-any.whl (3.5 kB)
Collecting pycosat>=0.6.1
  Downloading pycosat-0.6.3.zip (66 kB)
Requirement already satisfied: requests>=2.12.4 in /usr/local/lib/python3.8/dist-packages (from conda) (2.23.0)
Collecting ruamel.yaml>=0.11.14
  Downloading ruamel.yaml-0.17.21-py3-none-any.whl (109 kB)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.12.4->conda) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.12.4->conda) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.12.4->conda) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.12.4->conda) (2022.9.24)
Collecting ruamel.yaml.clib>=0.2.6
  Downloading ruamel.yaml.clib-0.2.7-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (555 kB)
Building wheels for collected packages: conda, pycosat, env
  Building wheel for conda (setup.py): started
  Building wheel for conda (setup.py): finished with status 'done'
  Created wheel for conda: filename=conda-4.3.16-py3-none-any.whl size=336959 sha256=f11e86bc3b4b55bb79c98eb098e2ff9f1c49c915c1a6c590fb75b926dded4318
  Stored in directory: /root/.cache/pip/wheels/6e/c5/70/e50a1a99d26cbe940549549b7601d484e0f0bc4b8f0ec49e36
  Building wheel for pycosat (setup.py): started
  Building wheel for pycosat (setup.py): finished with status 'done'
  Created wheel for pycosat: filename=pycosat-0.6.3-cp38-cp38-linux_x86_64.whl size=143283 sha256=f534678358329ce27fa9030c6025824a01103fe69de7f7f01843351e4c464da7
  Stored in directory: /root/.cache/pip/wheels/71/5b/2d/0a9247760f0f008abc0eae7c0127a8c1cddfe1145e4b170fc0
  Building wheel for env (setup.py): started
  Building wheel for env (setup.py): finished with status 'done'
  Created wheel for env: filename=env-0.1.0-py3-none-any.whl size=2015 sha256=179a4795a7c47f45e68c212ce9ecd782fa885aa19d9885096b5202f34bc0f46c
  Stored in directory: /root/.cache/pip/wheels/c6/98/23/cb81525f9bf600cdf4976cc3c27a5a1d1ecab4911ef99a13bf
Successfully built conda pycosat env
Installing collected packages: ruamel.yaml.clib, ruamel.yaml, pycosat, export, env, conda
Successfully installed conda-4.3.16 env-0.1.0 export-0.2.0 pycosat-0.6.3 ruamel.yaml-0.17.21 ruamel.yaml.clib-0.2.7
